# Generated by Django 6.0.7 on 2026-07-14 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='slot',
            name='slot_doctor_start_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.slot', verbose_name='Слот'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Ожидание оплаты'), ('PAID', 'Оплачено'), ('EXPIRED', 'Истёк'), ('CANCELLED_BY_PATIENT', 'Отменено пациентом'), ('CANCELLED_BY_CLINIC', 'Отменено клиникой'), ('COMPLETED', 'Завершена'), ('NO_SHOW', 'Неявка')], max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
